### ISSUE TITLE
Change timeArray as you can change dayTable

### ISSUE THREAD

**Issue by jokrah** [burhanahmeed/vue-daily-schedule#12]
First of all, great work! It looks and behaves really good.

Is it possible to change the timeArray as well?

At the moment I cannot find a solution to change the time to a custom hour range without changing the internal state of your component. Maybe I just didnt found the prop or do we have to extend your Component to offer this?

Thanks a lot in advance!

**Comment by burhanahmeed** [comment]
Hi, thanks for using it!

did `steps` props work for you ? It will change current default interval `60` minutes to your desired range.
what kind of custom hour range do you mean?

**Comment by jokrah** [comment]
Hi @burhanahmeed, thank's for your fast reply. 

I'm looking more for changing the hours range from showing only 7:00 till 19:00 (it's the timeArray in your code). At the moment you can select any hours between 0 and 23. But as my use case is not offering a selection in the night, I would like to remove those boxes. Hope it's more clear now

**Comment by burhanahmeed** [comment]
ah got it, will take a loot at it soon
